version: 2
jobs:
  build:
    docker:
      - image: elixir:latest
        environment:
          - MIX_ENV=test
      - image: postgres:alpine
        environment:
          POSTGRES_USER: ubuntu
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run:
          name: Install dependencies and compile
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
      - run: mix ecto.create
      - run: mix credo
      - run: mix test
